# Generated by Django 4.2 on 2025-12-18 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Pozo')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='Ubicación/Campo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pozo',
                'verbose_name_plural': 'Pozos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha de Medición')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='surveys.well')),
            ],
            options={
                'verbose_name': 'Survey',
                'verbose_name_plural': 'Surveys',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SurveyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md', models.FloatField(verbose_name='Measured Depth (MD)')),
                ('inclination', models.FloatField(verbose_name='Inclinación (deg)')),
                ('azimuth', models.FloatField(verbose_name='Azimuth (deg)')),
                ('tvd', models.FloatField(blank=True, null=True, verbose_name='TVD')),
                ('north', models.FloatField(blank=True, null=True, verbose_name='North')),
                ('east', models.FloatField(blank=True, null=True, verbose_name='East')),
                ('survey_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='surveys.surveyheader')),
            ],
            options={
                'verbose_name': 'Dato de Survey',
                'verbose_name_plural': 'Datos de Survey',
                'ordering': ['md'],
            },
        ),
    ]
