# Generated by Django 4.2 on 2025-12-18 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_surveyimport_trajectory_trajectorystation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoreholeGeometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(help_text='Casing, Liner, Open Hole, Tubing', max_length=50, verbose_name='Tipo de Elemento')),
                ('start_md', models.FloatField(verbose_name='Profundidad Inicial (MD)')),
                ('end_md', models.FloatField(verbose_name='Profundidad Final (MD)')),
                ('diameter', models.FloatField(help_text='Diámetro nominal para visualización', verbose_name='Diámetro (in)')),
                ('color', models.CharField(default='#808080', help_text='Color para el 3D (ej: #FF0000)', max_length=20, verbose_name='Color Hex')),
                ('trajectory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geometry', to='surveys.trajectory')),
            ],
            options={
                'verbose_name': 'Geometría del Pozo',
                'verbose_name_plural': 'Geometría del Pozo',
                'ordering': ['start_md'],
            },
        ),
    ]
